services:
  grm-website:
    container_name: grm-website
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    hostname: grm-website

    ports:
      - "30007:80"

    networks:
      - default

networks:
  default:
    name: proxy-net
    external: true